/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#454652",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "outline": "#767683",
        "outline-variant": "#c6c5d4",
        "surface-tint": "#4c56af",
        "primary": "#000666",
        "on-primary": "#ffffff",
        "primary-container": "#1a237e",
        "on-primary-container": "#8690ee",
        "inverse-primary": "#bdc2ff",
        "secondary": "#843ab4",
        "on-secondary": "#ffffff",
        "secondary-container": "#cc80fd",
        "on-secondary-container": "#580087",
        "tertiary": "#001e25",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00353f",
        "on-tertiary-container": "#00a6bf",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e0e0ff",
        "primary-fixed-dim": "#bdc2ff",
        "on-primary-fixed": "#000767",
        "on-primary-fixed-variant": "#343d96",
        "secondary-fixed": "#f4d9ff",
        "secondary-fixed-dim": "#e4b5ff",
        "on-secondary-fixed": "#2f004b",
        "on-secondary-fixed-variant": "#6a1b9a",
        "tertiary-fixed": "#a8edff",
        "tertiary-fixed-dim": "#49d7f4",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary-fixed-variant": "#004e5b",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      boxShadow: {
        "elevation-1": "0px 4px 20px rgba(26, 35, 126, 0.05)",
        "elevation-2": "0px 10px 30px rgba(26, 35, 126, 0.12)",
        "modal": "0px 20px 50px rgba(26, 35, 126, 0.2)",
      }
    },
  },
  plugins: [],
}
