-- ============================================================
-- V5: EDUNOVA Multilingual Translation Tables
-- Supports: en (English), ta (Tamil), hi (Hindi)
-- ============================================================

CREATE TABLE IF NOT EXISTS opportunity_translations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id      VARCHAR(80) NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
    language_code       VARCHAR(5) NOT NULL,
    title               VARCHAR(400),
    description         TEXT,
    eligibility_summary TEXT,
    benefits_description TEXT,
    application_method  VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_opp_lang UNIQUE (opportunity_id, language_code)
);

CREATE INDEX IF NOT EXISTS idx_opp_trans_opp_id ON opportunity_translations (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_opp_trans_lang   ON opportunity_translations (language_code);

CREATE TABLE IF NOT EXISTS provider_translations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id         VARCHAR(80) NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    language_code       VARCHAR(5) NOT NULL,
    description         TEXT,
    mission             TEXT,
    who_they_support    TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_prov_lang UNIQUE (provider_id, language_code)
);

CREATE INDEX IF NOT EXISTS idx_prov_trans_prov_id ON provider_translations (provider_id);
CREATE INDEX IF NOT EXISTS idx_prov_trans_lang     ON provider_translations (language_code);
