-- V9: TamilNaduScholarshipMasterSchema — Structured slab tables + new eligibility fields
-- Implements the JSON schema with engineering cut-off slabs, 12th % slabs, income, tenure, renewal

-- ── 1. Engineering cut-off slab table ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS opportunity_cutoff_slabs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id          VARCHAR(80) NOT NULL
                                REFERENCES opportunities(id) ON DELETE CASCADE,
    min_cutoff              DECIMAL(6,2) NOT NULL,          -- e.g. 180.00
    max_cutoff              DECIMAL(6,2),                   -- NULL = no upper bound (≥ min)
    tuition_waiver_percent  DECIMAL(5,2) NOT NULL DEFAULT 0,
    hostel_bus_waiver_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    notes                   VARCHAR(255),
    sort_order              INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_opp_cutoff_slab UNIQUE (opportunity_id, min_cutoff)
);
CREATE INDEX IF NOT EXISTS idx_cutoff_opp ON opportunity_cutoff_slabs(opportunity_id);

-- ── 2. 12th percentage slab table ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS opportunity_percentage_slabs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id          VARCHAR(80) NOT NULL
                                REFERENCES opportunities(id) ON DELETE CASCADE,
    min_percent             DECIMAL(5,2) NOT NULL,          -- e.g. 60.00
    max_percent             DECIMAL(5,2),                   -- NULL = no upper bound
    benefit_percentage      DECIMAL(5,2) NOT NULL,          -- tuition waiver %
    hostel_waiver_percent   DECIMAL(5,2) NOT NULL DEFAULT 0,
    notes                   VARCHAR(255),
    sort_order              INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_opp_pct_slab UNIQUE (opportunity_id, min_percent)
);
CREATE INDEX IF NOT EXISTS idx_pct_opp ON opportunity_percentage_slabs(opportunity_id);

-- ── 3. New columns on opportunity_eligibility ──────────────────────────────────
ALTER TABLE opportunity_eligibility
    ADD COLUMN IF NOT EXISTS requires_income_certificate BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS min_engineering_cutoff      DECIMAL(6,2),
    ADD COLUMN IF NOT EXISTS parent_id_card_type         VARCHAR(80),
    ADD COLUMN IF NOT EXISTS eligible_categories_json    VARCHAR(500);  -- JSON array stored as string

-- ── 4. New columns on opportunities (tenure/renewal) ──────────────────────────
ALTER TABLE opportunities
    ADD COLUMN IF NOT EXISTS duration_type          VARCHAR(40) DEFAULT 'FULL_COURSE',
    ADD COLUMN IF NOT EXISTS min_cgpa_renewal       DECIMAL(4,2),
    ADD COLUMN IF NOT EXISTS no_standing_arrears    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS verified_year          VARCHAR(10) DEFAULT '2026';

-- ── 5. Populate cutoff slabs for EXISTING opportunities ────────────────────────

-- RIT Sabari 190 (100% free)
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES ('opp-rit-sabari-190-free', 190.00, NULL, 100.00, 0.00, '100% free seat via Sabari Foundation', 1)
ON CONFLICT DO NOTHING;

-- RIT Sabari 180 (50%)
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES ('opp-rit-sabari-180-half', 180.00, 189.99, 50.00, 0.00, '50% tuition waiver for cut-off 180–189.99', 1)
ON CONFLICT DO NOTHING;

-- ── 6. Populate cutoff slabs for NEW opportunities ─────────────────────────────

-- VSB Engineering: 3 slabs
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES
  ('opp-vsb-eng-190', 190.00, NULL,   100.00, 50.00, '100% tuition + 50% hostel + 50% bus above 190', 1),
  ('opp-vsb-eng-185', 185.00, 189.75, 100.00, 0.00,  '100% tuition for 185–189.75', 1),
  ('opp-vsb-eng-180', 180.00, 184.75, 50.00,  0.00,  '50% tuition for 180–184.75', 1)
ON CONFLICT DO NOTHING;

-- Kathir College: 3 slabs
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES
  ('opp-kathir-190', 190.00, NULL,   100.00, 0.00, '100% tuition waiver for ≥190', 1),
  ('opp-kathir-180', 180.00, 189.99, 50.00,  0.00, '50% tuition waiver for 180–189.99', 2)
ON CONFLICT DO NOTHING;

-- CARE College: 3 slabs
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES
  ('opp-care-190', 190.00, NULL,   100.00, 0.00, '100% tuition for 190+', 1),
  ('opp-care-180', 180.00, 189.99, 75.00,  0.00, '75% tuition for 180–189', 2)
ON CONFLICT DO NOTHING;

-- CMS College: 4 slabs (cut-off scale)
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES
  ('opp-cms-175', 175.00, NULL,   100.00, 0.00, '100% tuition for cut-off 175+', 1),
  ('opp-cms-175', 171.00, 174.99, 75.00,  0.00, '75% tuition for 171–175', 2),
  ('opp-cms-175', 166.00, 170.99, 50.00,  0.00, '50% tuition for 166–170', 3),
  ('opp-cms-175', 160.00, 165.99, 25.00,  0.00, '25% tuition for 160–165', 4)
ON CONFLICT DO NOTHING;

-- KSR Merit
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES ('opp-ksr-merit-sat', 190.00, NULL, 100.00, 0.00, 'Top cut-off → 100%. Full slab per KSR SAT results.', 1)
ON CONFLICT DO NOTHING;

-- SNS 100%
INSERT INTO opportunity_cutoff_slabs (opportunity_id, min_cutoff, max_cutoff, tuition_waiver_percent, hostel_bus_waiver_percent, notes, sort_order)
VALUES ('opp-sns-full-scholarship', 175.00, NULL, 100.00, 0.00, '100% full scholarship for cut-off ≥175', 1)
ON CONFLICT DO NOTHING;

-- ── 7. Populate percentage slabs for EXISTING + NEW opportunities ──────────────

-- Saveetha/SIMATS: 4 % slabs
INSERT INTO opportunity_percentage_slabs (opportunity_id, min_percent, max_percent, benefit_percentage, hostel_waiver_percent, notes, sort_order)
VALUES
  ('opp-saveetha-90-100', 90.00, 100.00, 100.00, 0.00, '100% tuition for 90–100%', 1),
  ('opp-saveetha-90-100', 80.00,  89.99,  75.00, 0.00, '75% tuition for 80–89.9%', 2),
  ('opp-saveetha-90-100', 70.00,  79.99,  50.00, 0.00, '50% tuition for 70–79.9%', 3),
  ('opp-saveetha-90-100', 60.00,  69.99,  25.00, 0.00, '25% tuition for 60–69.9%', 4)
ON CONFLICT DO NOTHING;

-- VIT Chennai % slab
INSERT INTO opportunity_percentage_slabs (opportunity_id, min_percent, max_percent, benefit_percentage, hostel_waiver_percent, notes, sort_order)
VALUES
  ('opp-vit-chennai-topper', 90.00, 100.00, 80.00, 0.00, '80% tuition for school topper ≥90%', 1)
ON CONFLICT DO NOTHING;

-- ── 8. Update tenure/duration type for new and existing opportunities ──────────
UPDATE opportunities SET duration_type = 'FULL_COURSE'  WHERE full_course_or_first_year = 'FULL_COURSE';
UPDATE opportunities SET duration_type = 'ONE_TIME'     WHERE full_course_or_first_year = 'FIRST_YEAR';

-- ── 9. Update verified_year for active records ─────────────────────────────────
UPDATE opportunities SET verified_year = '2026'
  WHERE verification_status IN ('ACTIVE','VERIFIED','VERIFY_CURRENT_CYCLE');
